### ISSUE TITLE
1.11 roadmap

### ISSUE THREAD

**Issue by rdb** [panda3d/panda3d#1604]
This is an overview of the big (remaining) chunks on the way towards the 1.11 release, to keep this information in one place.  This is meant to be a "living issue" and will be updated as plans change.  Bugs (other than major blockers) are not listed, only big items, that may be subdivided further in linked issues.  Discussion is welcome but I don't want to turn this issue into a wishlist issue, let's focus on just the important things.

[List of all associated issues](https://github.com/panda3d/panda3d/milestone/4)

## Deprecations
Supported minimum OS versions are macOS 10.9, Windows 7, and manylinux2014 (or compatible).  Supported Python version is minimum 3.8, which is the last version to support Windows 7.
- [x] #300
- [x] #548
- [x] #905

## Shaders / graphics
- [ ] #1381
- [ ] #1388
- [ ] (may be dropped) #1005

## Platform support
At this point I'm suggesting not to hold up the release for these.
- [ ] Android
	- [x] Support Android deployment in build_apps
	- [ ] #1216
	- [ ] Build pipeline for Android wheels
	- [ ] Finish and merge multitouch branch
- [ ] WebGL
	- [x] Implement WebGL back-end
	- [ ] Set up CI for WebGL and merge into master
	- [ ] #1540

## Making Panda3D easier to build and maintain
- [ ] Switch to CMake build system
	- [x] #717
	- [ ] #1310
	- [ ] #859
- [ ] #1311
- [ ] #1589
- [ ] #1584

## GSoC Projects
These would be nice to have in 1.11 (but not critical if we can't get them finished)
- [x] #691
- [ ] #1268

## Behaviour/API changes
Changes that are not hard or urgent but need to be considered at a major release point.
- [ ] #377
- [ ] #867
- [ ] #1386
- [ ] #1466
